name: Master test and push

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
    
    - name: Build
      run: dotnet build --configuration Release
    
    - name: Unit Tests
      run: dotnet test
    
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@9885a4f9af674ba472de91fb3c0cb033ecb32b7e
      id: new_version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        INITIAL_VERSION: 1.0.0
        WITH_V: false
    
    - name: DockerHub Build and push Simulator Docker Image
      uses: docker/build-push-action@v1.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: iottelemetrysimulator/azureiot-telemetrysimulator
        tags: latest, ${{ steps.new_version.outputs.tag }}
        dockerfile: src/IotTelemetrySimulator/Dockerfile
        push: true
        
    - name: DockerHub Build and push Provisioning Docker Image
      uses: docker/build-push-action@v1.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: iottelemetrysimulator/azureiot-simulatordeviceprovisioning
        tags: latest, ${{ steps.new_version.outputs.tag }}
        dockerfile: src/IotSimulatorDeviceProvisioning/Dockerfile
        push: true

    - name: Azure Coontainer Registry Build and push Docker Images
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_URL }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - run: |
        docker build -f src/IotSimulatorDeviceProvisioning/Dockerfile -t ${{ secrets.ACR_URL }}/public/oss/azure-samples/azureiot-simulatordeviceprovisioning:${{ steps.new_version.outputs.tag }} .
        docker push ${{ secrets.ACR_URL }}/public/oss/azure-samples/azureiot-simulatordeviceprovisioning:${{ steps.new_version.outputs.tag }}
        docker tag ${{ secrets.ACR_URL }}/public/oss/azure-samples/azureiot-simulatordeviceprovisioning:${{ steps.new_version.outputs.tag }} ${{ secrets.ACR_URL }}/public/oss/azure-samples/azureiot-simulatordeviceprovisioning:latest
        docker push ${{ secrets.ACR_URL }}/public/oss/azure-samples/azureiot-simulatordeviceprovisioning:latest
        
        docker build -f src/IotTelemetrySimulator/Dockerfile -t ${{ secrets.ACR_URL }}/public/oss/azure-samples/azureiot-telemetrysimulator:${{ steps.new_version.outputs.tag }} .
        docker push ${{ secrets.ACR_URL }}/public/oss/azure-samples/azureiot-telemetrysimulator:${{ steps.new_version.outputs.tag }}
        docker tag ${{ secrets.ACR_URL }}/public/oss/azure-samples/azureiot-telemetrysimulator:${{ steps.new_version.outputs.tag }} ${{ secrets.ACR_URL }}/public/oss/azure-samples/azureiot-telemetrysimulator:latest
        docker push ${{ secrets.ACR_URL }}/public/oss/azure-samples/azureiot-telemetrysimulator:latest
